library(sf)
library(terra)
library(dplyr)
library(ggplot2)
library(readr)
# install.packages("~/GECOr-stineb/")
library(GECOr)
library(ggridges)

sf::sf_use_s2(FALSE)

# file generated by analysis/plot_map_biomes.R
df_biomes <- terra::rast(here::here("data/biomes_raster_0.1deg.tif")) |> 
  as.data.frame(xy = TRUE) |> 
  as_tibble() |> 
  mutate(x = as.integer(round(100 * x)),
         y = as.integer(round(100 * y)))

x_df_biomes <- df_biomes |> pull(x)

# Veg height -------------------
# read 0.05 deg data
# read file from GECO data archive
rasta <- terra::rast("~/data/archive/vegheight_simard_2011/data/vegheight_simard_2011.nc")

# re-grid to 0.1 deg
rasta_lo <- terra::aggregate(rasta, fact = 2, fun = "mean")

gg <- plot_map4(rasta_lo,
                latmin = -60, 
                latmax = 85,
                legend_title = "(m)",
                colorscale = "bamako", 
                combine = FALSE,
                ocean = TRUE
                )
gg$ggmap <- gg$ggmap + 
  labs(title = "Vegetation height")
cowplot::plot_grid(gg$ggmap, gg$gglegend, ncol = 2, rel_widths = c(1, 0.12))

ggsave(here::here("book/images/map_vegheight.png"), width = 8, height = 5)
ggsave(here::here("book/images/map_vegheight.pdf"), width = 8, height = 5)

## By biome ---------------
df_vegheight <- rasta_lo |> 
  as.data.frame(xy = TRUE) |> 
  as_tibble() |> 
  mutate(x = as.integer(round(100 * x)),
         y = as.integer(round(100 * y)))

x_df_vegheight <- df_vegheight |> 
  pull(x)

df_joined <- df_vegheight |> 
  left_join(
    df_biomes, 
    by = c("x", "y")
  )

df_joined |> 
  ggplot(aes(Band1, WWF_MHTNAM)) +
  geom_boxplot()

biome_exclude <- c("Rock and Ice", "Inland Water")

gg <- df_joined |> 
  dplyr::filter(!(WWF_MHTNAM %in% biome_exclude)) |>
  mutate(WWF_MHTNAM = factor(WWF_MHTNAM, levels = c("Tundra",
                                                    "BorealForests/Taiga",
                                                    "Montane Grasslands and Shrublands",
                                                    "TemperateConiferForests",
                                                    "Temperate Broadleaf and Mixed Forests",
                                                    "Mediterranean Forests, Woodlands and Scrub",
                                                    "Temperate Grasslands, Savannas and Shrublands",
                                                    "Deserts and Xeric Shrublands",
                                                    "Flooded Grasslands and Savannas",
                                                    "Mangroves",
                                                    "Tropical and Subtropical Grasslands, Savannas and Shrublands",
                                                    "Tropical and Subtropical Coniferous Forests",
                                                    "Tropical and Subtropical Dry Broadleaf Forests",
                                                    "Tropical and Subtropical Moist Broadleaf Forests"))) |> 
  dplyr::filter(!is.na(WWF_MHTNAM)) |>
  ggplot(aes(x = Band1, 
             y = WWF_MHTNAM)) +
  geom_density_ridges(
    jittered_points = FALSE, scale = .95, rel_min_height = .01, 
  ) +
  scale_y_discrete(expand = c(0, 0), name = "") +
  scale_x_continuous(expand = c(0, 0), name = "Vegetation height (m)", limits = c(0, 50)) +
  coord_cartesian(clip = "off")

ggsave(here::here("book/images/map_vegheight_biome.png"), plot = gg, width = 8, height = 5)
ggsave(here::here("book/images/map_vegheight_biome.pdf"), plot = gg, width = 8, height = 5)
