create_map_byvar <- function(path, 
                             varnam, 
                             labelnam,
                             longnam,
                             do_aggregate = FALSE, 
                             fact = 2, 
                             use_raster = TRUE,
                             transpose = FALSE,
                             units = "",
                             xaxis_ridgeplot = paste(longnam, units),
                             ...
){
  
  if (use_raster){
    rasta <- terra::rast(path)
    
    if (do_aggregate){
      rasta_lo <- terra::aggregate(rasta, fact = fact, fun = "mean")
    } else {
      rasta_lo <- rasta
    }
  } else {
    rasta_lo <- read_nc_onefile(path,
                          varnam = varnam)
    rasta_lo$vars[[varnam]] <- t(rasta_lo$vars[[varnam]])
  }
  
  # GECOr package from https://github.com/geco-bern/GECOr
  gg <- GECOr::plot_map4(rasta_lo,
                         varnam = varnam,
                         latmin = -60, 
                         latmax = 85,
                         combine = FALSE,
                         ocean = TRUE,
                         legend_title = units,
                         ...
  )
  gg$ggmap <- gg$ggmap + 
    labs(title = longnam)
  cowplot::plot_grid(gg$ggmap, gg$gglegend, ncol = 2, rel_widths = c(1, 0.12))
  
  filnam <- here::here(paste0("book/images/map_", labelnam, ".pdf"))
  message(paste("Writing figure:", filnam))
  ggsave(filnam, width = 8, height = 5)
  filnam <- here::here(paste0("book/images/map_", labelnam, ".png"))
  message(paste("Writing figure:", filnam))
  ggsave(filnam, width = 8, height = 5)
  
  ## By biome ---------------
  if (!use_raster){
    rasta <- terra::rast(path)
    if (do_aggregate){
      rasta_lo <- terra::aggregate(rasta, fact = fact, fun = "mean")
    } else {
      rasta_lo <- rasta
    }
  }
  
  # file generated by analysis/plot_map_biomes.R
  rasta_biomes <- terra::rast(here::here("data/biomes_raster_0.1deg.tif"))
  
  # regrid the rasta (raster object of variable of interest) to the grid of the biome raster
  rasta_biomes_lo <- terra::resample(rasta_biomes, rasta_lo, method = "near")
  
  df_biomes <- rasta_biomes_lo |> 
    as.data.frame(xy = TRUE) |> 
    as_tibble() 
  # mutate(x = as.integer(round(100 * x)),
  #        y = as.integer(round(100 * y)))
  
  df_raster <- rasta_lo |> 
    as.data.frame(xy = TRUE) |> 
    as_tibble() |> 
    # mutate(x = as.integer(round(100 * x)),
    #        y = as.integer(round(100 * y))) |> 
    select(x, y, layer = !!varnam)
  
  df_joined <- df_raster |> 
    left_join(
      df_biomes,
      by = c("x", "y")
    )
    
  # df_joined <- df_raster |> 
  #   slice(1:10) |> 
  #   left_join(
  #     df_biomes, 
  #     by = c("x", "y"),
  #     max_dist = 0.201, 
  #     method = "manhattan"
  #   )

  biome_exclude <- c("Rock and Ice", "Inland Water")
  
  gg <- df_joined |> 
    dplyr::filter(!(WWF_MHTNAM %in% biome_exclude)) |>
    mutate(WWF_MHTNAM = factor(WWF_MHTNAM, levels = c("Tundra",
                                                      "BorealForests/Taiga",
                                                      "Montane Grasslands and Shrublands",
                                                      "TemperateConiferForests",
                                                      "Temperate Broadleaf and Mixed Forests",
                                                      "Mediterranean Forests, Woodlands and Scrub",
                                                      "Temperate Grasslands, Savannas and Shrublands",
                                                      "Deserts and Xeric Shrublands",
                                                      "Flooded Grasslands and Savannas",
                                                      "Mangroves",
                                                      "Tropical and Subtropical Grasslands, Savannas and Shrublands",
                                                      "Tropical and Subtropical Coniferous Forests",
                                                      "Tropical and Subtropical Dry Broadleaf Forests",
                                                      "Tropical and Subtropical Moist Broadleaf Forests"))) |> 
    dplyr::filter(!is.na(WWF_MHTNAM)) |>
    ggplot(aes(x = layer, 
               y = WWF_MHTNAM)) +
    geom_density_ridges(
      jittered_points = FALSE, scale = .95, rel_min_height = .01, 
    ) +
    scale_y_discrete(expand = c(0, 0), name = "") +
    scale_x_continuous(expand = c(0, 0), name = xaxis_ridgeplot) +
    coord_cartesian(clip = "off")
  
  ggsave(here::here(paste0("book/images/map_", labelnam, "_biome.png")), plot = gg, width = 8, height = 5)
  ggsave(here::here(paste0("book/images/map_", labelnam, "_biome.pdf")), plot = gg, width = 8, height = 5)
  
}