---
format: 
  html:
    fig-width: 7
    fig-height: 5
  pdf:
    fig-width: 7
    fig-height: 5
---

# Ecosystem carbon dynamics {#sec-carboncycle_ecosystem}

In @sec-globalcarbonbudget, we conceived the global carbon cycle as a system of three pools (atmosphere, land, ocean). The C dynamics in the land biosphere were modeled using a 1-box model which receives C inputs through photosynthesis and loses C through a constant turnover. In @sec-gpp, we focused on the processes driving terrestrial CO~2~ uptake. In this chapter, we are unboxing the 1-box model and introduce the processes that determine C flows in ecosystems and their C balance. 

- Land: GPP-NPP, vegC, soilC, Ra, Rh

## Plant-level carbon balance

- The carbon cascade {#sec-cascade }
- The C cascade: Tree growth, allocation, mortality, forest dynamics
- multi-box model

### Net primary productivity {#sec-npp}

- carbon use efficiency and its relative constancy
- biomass productivity

### Allocation

### Turnover

### The C cascade

<!-- Forest dynamics -->

<!-- Very Simple Ecosystem Model -->

<!-- - Tree allometry -->
<!-- - Self-thinning -->
<!-- - Disturbance and succession -->
<!-- - Tree mortality -->
<!-- McDowell et al., 2022 https://doi.org/10.1038/s43017-022-00272-1 -->
<!-- - Models -->
<!--     - von-Foerster Eq -->
<!--     - PPA -->
<!--     - gap dynamics -->
<!--     Bonan 23.3 -->