# Introduction

The Earth system can be regarded as a coupled system in which its elements (atmosphere, ocean, cryosphere, biosphere, pedosphere, lithosphere) are interacting on various time scales. A primary goal of Earth System research is to understand the interactions occurring on time scales that are relevant for society in the context of anthropogenic climate change. It is now established with overwhelming evidence that anthropogenic CO2 emissions from the combustion of fossil fuels have caused a rise in atmospheric CO2 concentrations beyond levels reached over the past 800,000 years, and that this concentration increase is the dominant driver of climate change as observed over the last decades.

The terrestrial biosphere - land - is at the core of the Earth system. It connects all spheres. Atmospheric humidity and near-surface heating of the atmosphere are determined by how much water vegetation transpires and how much radiation it reflects or absorbs. Its carbon balance determines the accumulation of anthropogenic CO2 in the atmosphere and thus affects the CO2 gas exchange between the ocean and the atmosphere. The activity of plants is the driver for processes in the soil, the weathering of rocks. Any projection of climate change and climate impacts for the coming decades, centuries and millennia relies on an understanding of how the terrestrial biosphere responds and feeds back to climate and the Earth system. The carbon cycle of the terrestrial biosphere has a strong influence on how fast anthropogenic CO2 emissions will accumulate in the atmosphere. And it is through land ecosystems - both natural and agricultural - that climate impacts will be most clearly expressed. Understanding how climate influences the terrestrial biosphere is thus key to understanding climate impacts and projecting Earth system change.

This book focuses on the terrestrial biosphere, how its structure and functioning are shaped by climate, and how it affects atmospheric CO2 and climate change. The following set of phenomena and observations of current global environmental change impacts are an expression of the key role of the land in the Earth system. Over the course of this book, we will revisit these phenomena and observations and introduce the underlying processes and principles for understanding them. 


<!-- This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

```{r}
1 + 1
```
 -->